exclude = [
  "migrations",
]

# Same as Black.
line-length = 88
indent-width = 4

[format]
# Unlike Black.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
